services:
  postgres:
    image: 'postgres:15-alpine'
    ports:
      - "${SQL_DATABASE_EXTERNAL_PORT}:${SQL_DATABASE_PORT}"
    environment:
      POSTGRES_PASSWORD: ${SQL_DATABASE_PASSWORD}
      POSTGRES_USER: ${SQL_DATABASE_USER}
      POSTGRES_DB: ${SQL_DATABASE_NAME}
  backend:
    build:
      context: ./
    ports:
      - "${SERVER_EXTERNAL_PORT}:${SERVER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SQL_DATABASE_HOST=${SQL_DATABASE_HOST}
      - SQL_DATABASE_PORT=${SQL_DATABASE_PORT}
      - SQL_DATABASE_NAME=${SQL_DATABASE_NAME}
      - SQL_DATABASE_USER=${SQL_DATABASE_USER}
      - SQL_DATABASE_PASSWORD=${SQL_DATABASE_PASSWORD}